version: '3.8'

services:
  MCEI.SysControlAdmin:
    build:
      context: .
      dockerfile: .MCEI.SysControlAdmin.WebApp/Dockerfile # Ruta relativa al Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development # Cambia según tu entorno
    volumes:
      - .:/app # Montar el directorio actual dentro del contenedor
