version: '3.8'

services:
  MCEI.SysControlAdmin:
    build:
      context: ./MCEI.SysControlAdmin.WebApp 
      dockerfile: Dockerfile
    ports:
      - "80:80"   # Exponer el puerto 80
      - "443:443" # Exponer el puerto 443
    environment:
      ASPNETCORE_ENVIRONMENT: Development # Ajusta según tus necesidades
    volumes:
      - ./MCEI.SysControlAdmin.WebApp:/app 
